third commit, nie dziala findAll Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.IllegalStateException: We need at least one condition] with root cause
                                 java.lang.IllegalStateException: We need at least one condition